spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ptcmss_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: dev

openapi:
  service:
    api-docs: Computer_sell
    server: http://localhost:8080
    title: Transport Application
    version: 1.0.0

server:
  port: 8080

management:
  endpoints:
    web.exposure.include: health,info


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ptcmss_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    username: root
#    password: 123456
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#openapi:
#  service:
#    api-docs: Computer_sell
#    server: http://localhost:8080
#    title: Transport Application
#    version: 1.0.0
#
#server:
#  port: 8080
#
#management:
#  endpoints:
#    web.exposure.include: health,info
#
#
