spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ptcmss_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
openapi:
  service:
    api-docs: Computer_sell
    server: http://localhost:8080
    title: Transport Application
    version: 1.0.0

server:
  port: 8080

management:
  endpoints:
    web.exposure.include: health,info
